# Source: jxboot-helmfile-resources/templates/repositories.yaml
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "dev"
  labels:
    jenkins.io/gitSync: "false"
    gitops.jenkins-x.io/pipeline: 'environment'
  namespace: jx
spec:
  description: "the git repository for the Dev environment"
  provider: "https://github.com"
  providerName: 'github'
  org: "cb-kubecd"
  repo: "env-pr-1187-3-bdd-gke-dev"
  httpCloneURL: "https://github.com/cb-kubecd/env-pr-1187-3-bdd-gke-dev.git"
  url: "https://github.com/cb-kubecd/env-pr-1187-3-bdd-gke-dev.git"
  scheduler:
    kind: Scheduler
    name: "environment"
